---
- hosts: localhost
  #remote_user: ubuntu
  become: true
  tasks:

    - name: Turn off DNS stub listender via resolved conf
      lineinfile:
        path: /etc/systemd/resolved.conf
        line: "DNSStubListener=no"
        state: present
        backup: yes

    - name: Reload service resolved, in all cases
      ansible.builtin.systemd:
        name: systemd-resolved
        state: reloaded

  # /etc/systemd/resolved.conf.d/dns_server.conf
    - name: Stop and disable systemd-resolved
      systemd:
        name: systemd-resolved
        state: stopped
        enabled: no